baseURL = "https://techtweedie.github.io/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Tech Tweedie"

# Change the default theme to be use when building the site with Hugo
theme = "FeelIt"

[params]
  # FeelIt theme version
  version = "1.0.X"
  # site description
  description = "Beyond the low code, Tech Tweedie offers comprehensive guides and tutorials on Power Platform, Microsoft technologies, and Hugo. Learn how to build PCF controls, install Hugo on Windows 11, and more. Stay updated with our latest posts and in-depth content."
  # site keywords
  keywords = ["Power Platform", "Microsoft", "Hugo", "PCF controls", "Windows 11", "Tech tutorials", "Static site generator", "TypeScript", "HTML", "Web development", "Power Apps", "Power Automate", "Power BI", "Dataverse", "Canvas Apps", "Model-driven Apps", "Power Platform Administration", "Power Platform Integration", "Power Platform Security"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # date format
  dateFormat = "2006-01-02"
  # website images for Open Graph and Twitter Cards
  images = ["/logo.png"]

# App icon config
[params.app]
  # optional site title override for the app when added to an iOS home screen or Android launcher
  title = "Tech Tweedie"
  # whether to omit favicon resource links
  noFavicon = false
  # modern SVG favicon to use in place of older style .png and .ico files
  svgFavicon = "/safari-pinned-tab.svg"
  # Android browser theme color
  themeColor = "#dddddd"
  # Safari mask icon color
  iconColor = "#dddddd"
  # Windows v8-10 tile color
  tileColor = "#dddddd" 
   
# Header config
[params.header]
  # desktop header mode ("fixed", "normal", "auto")
  desktopMode = "auto"
  # mobile header mode ("fixed", "normal", "auto")
  mobileMode = "auto"

 # Header title config
[params.header.title]
  # URL of the LOGO
  logo = "/logo-01_150x150.png"
  # title name
  name = "Tech Tweedie"
  # you can add extra information before the name (HTML format is supported), such as icons
  pre = " "
  # you can add extra information after the name (HTML format is supported), such as icons
  post = ""
  # whether to use typeit animation for title name
  typeit = true
  # whether to show RSS icon
  rss = true

  # Footer config
[params.footer]
  enable = true
  # Custom content (HTML format is supported)
  custom = 'Tech Tweedie Blog'
  # whether to show Hugo and theme info
  hugo = true
  #  whether to show copyright info
  copyright = true
  #  whether to show the author
  author = true
  # Site creation time
  since = 2019
  # license info (HTML format is supported)
  license = ''


[menu]
  [[menu.main]]
    identifier = "how-to"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "How to"
    url = "/categories/how-to/"
    # title will be shown when you hover on this menu link
    title = "How to"
    weight = 1
  [[menu.main]]
    identifier = "community"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Community"
    url = "/categories/community/"
    # title will be shown when you hover on this menu link
    title = "Supporting the Power Platform Community"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "YouTubeChannel"
    pre = ""
    post = ""
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCy1a2QSDVZNDwZf7KbNmoHQ"
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "FreePowerPlatformTools"
    pre = ""
    post = ""
    name = "Free Tools"
    url = "https://mightora.io/"
    title = ""
    weight = 5

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/khusika/FeelIt/issues/158)
    noClasses = false

# Home page config
[params.home]
  # amount of RSS pages
  rss = 100
  # Home page profile
[params.home.profile]
  enable = true
  # Gravatar Email for preferred avatar in home page
  # gravatarEmail = "ian.tweedie@hotmail.com"
  # URL of avatar shown in home page
  #avatarURL = "/logo-01_150x150_white.png"
  # title shown in home page (HTML format is supported)
  title = "Tech Tweedie Blog"
  # subtitle shown in home page
  subtitle = "Beyond the low code..."
  # whether to use typeit animation for subtitle
  typeit = true
  # whether to show social links
  social = true
  # disclaimer (HTML format is supported)
  disclaimer = ""
  
# Home page posts
[params.home.posts]
  enable = true
  # special amount of posts in each home posts page
  paginate = 18
  # display image-preview
  imagePreview = true
  # replaced with hiddenFromHomePage in params.page
  # default behavior when you don't set "hiddenFromHomePage" in front matter
  defaultHiddenFromHomePage = false

[params.social]
  GitHub = "itweedie"
  inkedin = "iantweedie"
  Twitter = "itweedie"
  Medium = "@ian.tweedie"
  Gitlab = "itweedie"
  Youtubelegacy = ""
  Youtubecustom = ""
  Youtubechannel = "UCy1a2QSDVZNDwZf7KbNmoHQ"

[params.verification]
  google = "SJUxP7HXovdJ6V7D8UPJm1ntx_D-yiuiC5XM70mnHCI"

# Analytics config
[params.analytics]
  enable = true
  # Google Analytics
  [params.analytics.google]
    # GA Tracking ID
    id = "G-2GHVQK02Y4"
    # whether to anonymize IP
    anonymizeIP = true
  # GoatCounter Analytics
  [params.analytics.goatcounter]
    # GoatCounter code
      code = "techtweedie"


 [params.cookieconsent]
  enable = true
  # text strings used for Cookie consent banner
  # 用于 Cookie 许可横幅的文本字符串
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

# Social share links in post page
[params.page.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = true
    Whatsapp = true
    Pinterest = false
    Tumblr = false
    HackerNews = false
    Reddit = false
    VK = false
    Buffer = false
    Xing = false
    Line = false
    Instapaper = false
    Pocket = false
    Digg = false
    Stumbleupon = false
    Flipboard = false
    Weibo = false
    Renren = false
    Myspace = false
    Blogger = false
    Baidu = false
    Odnoklassniki = false
    Evernote = false
    Skype = false
    Trello = false
    Mix = false
